
name: deploy


on:
  push:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with: 
        version: 12
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: install 
    
    - name: Creating build
      run: yarn build
    
    - name: installing surge  
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build http://welcometo.surge.sh/ --token ${{secrets.GOOD}}
